{% set name = "lava-optimization" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lava-nc/lava-optimization/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 22fe8a50d47404563f342afe507ff5177040872664dba6bdd1598df8eb31d303
  patches:
    - fix-setup-py.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    # only required to get the version from build.py
    - pybuilder
  run:
    - python >=3.6
    - numpy
    - lava

test:
  source_files:
    - tests
  imports:
    - lava.lib.optimization.problems.problems
    - lava.lib.optimization.solvers
    - lava.lib.optimization.solvers.qp.solver
  commands:
    - python -m unittest

about:
  home: https://github.com/lava-nc/lava-optimization
  summary: A library of solvers that leverage neuromorphic hardware for constrained optimization.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - mgkwill
