{% set name = "lava-optimization" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lava-nc/lava-optimization/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 67e8f80028a9334722e3b797a0818e77ca7c385c3e7521d6d1030b5235cf5f1c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.11
    - poetry
  run:
    - python >=3.6,<3.11
    - numpy
    - lava
    - pandas
    - networkx
    - schema
    - scikit-optimize
    - scipy

test:
  source_files:
    - tests
  imports:
    - lava.lib.optimization.problems.problems
    - lava.lib.optimization.solvers
    - lava.lib.optimization.solvers.generic.qp.solver
  commands:
    - ipython kernel install --name "python3" --user
    - python -m unittest
  requires:
    - asteval
    - nbformat
    - nbconvert
    - ipython
    - ipykernel

about:
  home: https://github.com/lava-nc/lava-optimization
  summary: A library of solvers that leverage neuromorphic hardware for constrained optimization.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - mgkwill
